/*
 * This file is generated by jOOQ.
 */
package com.jay.getinline.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Admin implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long          id;
    private final LocalDateTime createdAt;
    private final String        email;
    private final String        memo;
    private final LocalDateTime modifiedAt;
    private final String        nickname;
    private final String        password;
    private final String        phoneNumber;

    public Admin(Admin value) {
        this.id = value.id;
        this.createdAt = value.createdAt;
        this.email = value.email;
        this.memo = value.memo;
        this.modifiedAt = value.modifiedAt;
        this.nickname = value.nickname;
        this.password = value.password;
        this.phoneNumber = value.phoneNumber;
    }

    public Admin(
        Long          id,
        LocalDateTime createdAt,
        String        email,
        String        memo,
        LocalDateTime modifiedAt,
        String        nickname,
        String        password,
        String        phoneNumber
    ) {
        this.id = id;
        this.createdAt = createdAt;
        this.email = email;
        this.memo = memo;
        this.modifiedAt = modifiedAt;
        this.nickname = nickname;
        this.password = password;
        this.phoneNumber = phoneNumber;
    }

    /**
     * Getter for <code>getinline.admin.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>getinline.admin.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Getter for <code>getinline.admin.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Getter for <code>getinline.admin.memo</code>.
     */
    public String getMemo() {
        return this.memo;
    }

    /**
     * Getter for <code>getinline.admin.modified_at</code>.
     */
    public LocalDateTime getModifiedAt() {
        return this.modifiedAt;
    }

    /**
     * Getter for <code>getinline.admin.nickname</code>.
     */
    public String getNickname() {
        return this.nickname;
    }

    /**
     * Getter for <code>getinline.admin.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Getter for <code>getinline.admin.phone_number</code>.
     */
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Admin (");

        sb.append(id);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(email);
        sb.append(", ").append(memo);
        sb.append(", ").append(modifiedAt);
        sb.append(", ").append(nickname);
        sb.append(", ").append(password);
        sb.append(", ").append(phoneNumber);

        sb.append(")");
        return sb.toString();
    }
}
