/*
 * This file is generated by jOOQ.
 */
package com.jay.getinline.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdminPlaceMap implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long          id;
    private final LocalDateTime createdAt;
    private final LocalDateTime modifiedAt;
    private final Long          adminId;
    private final Long          placeId;

    public AdminPlaceMap(AdminPlaceMap value) {
        this.id = value.id;
        this.createdAt = value.createdAt;
        this.modifiedAt = value.modifiedAt;
        this.adminId = value.adminId;
        this.placeId = value.placeId;
    }

    public AdminPlaceMap(
        Long          id,
        LocalDateTime createdAt,
        LocalDateTime modifiedAt,
        Long          adminId,
        Long          placeId
    ) {
        this.id = id;
        this.createdAt = createdAt;
        this.modifiedAt = modifiedAt;
        this.adminId = adminId;
        this.placeId = placeId;
    }

    /**
     * Getter for <code>getinline.admin_place_map.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>getinline.admin_place_map.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Getter for <code>getinline.admin_place_map.modified_at</code>.
     */
    public LocalDateTime getModifiedAt() {
        return this.modifiedAt;
    }

    /**
     * Getter for <code>getinline.admin_place_map.admin_id</code>.
     */
    public Long getAdminId() {
        return this.adminId;
    }

    /**
     * Getter for <code>getinline.admin_place_map.place_id</code>.
     */
    public Long getPlaceId() {
        return this.placeId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AdminPlaceMap (");

        sb.append(id);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(modifiedAt);
        sb.append(", ").append(adminId);
        sb.append(", ").append(placeId);

        sb.append(")");
        return sb.toString();
    }
}
