server:
  port: 8078
  error:
    whitelabel:
      enabled: false # 기본 에러 페이지를 비활성화

## 없어도 됨
#spring:
#  mvc:
#    view:
#      suffix: .html

# /actuator 경로를 통해 endpoint 전체 개요를 볼 수 있도록 하는 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"

#debug: true

logging:
  level:
    # 특정 path(root)를 debug 레벨로 관찰
    com.jay.getinline: debug
    # api 호출 과정을 debug 레벨로 관찰
    org.springframeworkd.web.servlet: debug

spring:
  config:
    activate:
      on-profile: jay
  # bean 등록 시기를 실제로 해당 서비스를 사용할 때 등록하도록 설정 - 서버 시작은 빨라지나 서비스 속도는 느려질 수 있음
#  main:
#    lazy-initialization: true
  thymeleaf:
    cache: false
  thymeleaf3:
    decoupled-logic: true

# profile 구분자
---

# 다른 profile
spring:
  config:
    activate:
      on-profile: kay
      # 옛날 설정 가능하도록 하는 설정
#    use-legacy-processing: true