server:
  port: 8078
  error:
    whitelabel:
      enabled: false # 기본 에러 페이지를 비활성화

## 없어도 됨
#spring:
#  mvc:
#    view:
#      suffix: .html

# /actuator 경로를 통해 endpoint 전체 개요를 볼 수 있도록 하는 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"
