/*
 * This file is generated by jOOQ.
 */
package com.jay.getinline.tables.records;


import com.jay.getinline.tables.Admin;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdminRecord extends UpdatableRecordImpl<AdminRecord> implements Record8<Long, LocalDateTime, String, String, LocalDateTime, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>getinline.admin.id</code>.
     */
    public AdminRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>getinline.admin.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>getinline.admin.created_at</code>.
     */
    public AdminRecord setCreatedAt(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>getinline.admin.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>getinline.admin.email</code>.
     */
    public AdminRecord setEmail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>getinline.admin.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>getinline.admin.memo</code>.
     */
    public AdminRecord setMemo(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>getinline.admin.memo</code>.
     */
    public String getMemo() {
        return (String) get(3);
    }

    /**
     * Setter for <code>getinline.admin.modified_at</code>.
     */
    public AdminRecord setModifiedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>getinline.admin.modified_at</code>.
     */
    public LocalDateTime getModifiedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>getinline.admin.nickname</code>.
     */
    public AdminRecord setNickname(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>getinline.admin.nickname</code>.
     */
    public String getNickname() {
        return (String) get(5);
    }

    /**
     * Setter for <code>getinline.admin.password</code>.
     */
    public AdminRecord setPassword(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>getinline.admin.password</code>.
     */
    public String getPassword() {
        return (String) get(6);
    }

    /**
     * Setter for <code>getinline.admin.phone_number</code>.
     */
    public AdminRecord setPhoneNumber(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>getinline.admin.phone_number</code>.
     */
    public String getPhoneNumber() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, LocalDateTime, String, String, LocalDateTime, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, LocalDateTime, String, String, LocalDateTime, String, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Admin.ADMIN.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return Admin.ADMIN.CREATED_AT;
    }

    @Override
    public Field<String> field3() {
        return Admin.ADMIN.EMAIL;
    }

    @Override
    public Field<String> field4() {
        return Admin.ADMIN.MEMO;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Admin.ADMIN.MODIFIED_AT;
    }

    @Override
    public Field<String> field6() {
        return Admin.ADMIN.NICKNAME;
    }

    @Override
    public Field<String> field7() {
        return Admin.ADMIN.PASSWORD;
    }

    @Override
    public Field<String> field8() {
        return Admin.ADMIN.PHONE_NUMBER;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreatedAt();
    }

    @Override
    public String component3() {
        return getEmail();
    }

    @Override
    public String component4() {
        return getMemo();
    }

    @Override
    public LocalDateTime component5() {
        return getModifiedAt();
    }

    @Override
    public String component6() {
        return getNickname();
    }

    @Override
    public String component7() {
        return getPassword();
    }

    @Override
    public String component8() {
        return getPhoneNumber();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreatedAt();
    }

    @Override
    public String value3() {
        return getEmail();
    }

    @Override
    public String value4() {
        return getMemo();
    }

    @Override
    public LocalDateTime value5() {
        return getModifiedAt();
    }

    @Override
    public String value6() {
        return getNickname();
    }

    @Override
    public String value7() {
        return getPassword();
    }

    @Override
    public String value8() {
        return getPhoneNumber();
    }

    @Override
    public AdminRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AdminRecord value2(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public AdminRecord value3(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public AdminRecord value4(String value) {
        setMemo(value);
        return this;
    }

    @Override
    public AdminRecord value5(LocalDateTime value) {
        setModifiedAt(value);
        return this;
    }

    @Override
    public AdminRecord value6(String value) {
        setNickname(value);
        return this;
    }

    @Override
    public AdminRecord value7(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public AdminRecord value8(String value) {
        setPhoneNumber(value);
        return this;
    }

    @Override
    public AdminRecord values(Long value1, LocalDateTime value2, String value3, String value4, LocalDateTime value5, String value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdminRecord
     */
    public AdminRecord() {
        super(Admin.ADMIN);
    }

    /**
     * Create a detached, initialised AdminRecord
     */
    public AdminRecord(Long id, LocalDateTime createdAt, String email, String memo, LocalDateTime modifiedAt, String nickname, String password, String phoneNumber) {
        super(Admin.ADMIN);

        setId(id);
        setCreatedAt(createdAt);
        setEmail(email);
        setMemo(memo);
        setModifiedAt(modifiedAt);
        setNickname(nickname);
        setPassword(password);
        setPhoneNumber(phoneNumber);
    }
}
