/*
 * This file is generated by jOOQ.
 */
package com.jay.getinline.tables.records;


import com.jay.getinline.tables.AdminPlaceMap;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdminPlaceMapRecord extends UpdatableRecordImpl<AdminPlaceMapRecord> implements Record5<Long, LocalDateTime, LocalDateTime, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>getinline.admin_place_map.id</code>.
     */
    public AdminPlaceMapRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>getinline.admin_place_map.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>getinline.admin_place_map.created_at</code>.
     */
    public AdminPlaceMapRecord setCreatedAt(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>getinline.admin_place_map.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>getinline.admin_place_map.modified_at</code>.
     */
    public AdminPlaceMapRecord setModifiedAt(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>getinline.admin_place_map.modified_at</code>.
     */
    public LocalDateTime getModifiedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>getinline.admin_place_map.admin_id</code>.
     */
    public AdminPlaceMapRecord setAdminId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>getinline.admin_place_map.admin_id</code>.
     */
    public Long getAdminId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>getinline.admin_place_map.place_id</code>.
     */
    public AdminPlaceMapRecord setPlaceId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>getinline.admin_place_map.place_id</code>.
     */
    public Long getPlaceId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, LocalDateTime, LocalDateTime, Long, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, LocalDateTime, LocalDateTime, Long, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return AdminPlaceMap.ADMIN_PLACE_MAP.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return AdminPlaceMap.ADMIN_PLACE_MAP.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return AdminPlaceMap.ADMIN_PLACE_MAP.MODIFIED_AT;
    }

    @Override
    public Field<Long> field4() {
        return AdminPlaceMap.ADMIN_PLACE_MAP.ADMIN_ID;
    }

    @Override
    public Field<Long> field5() {
        return AdminPlaceMap.ADMIN_PLACE_MAP.PLACE_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component3() {
        return getModifiedAt();
    }

    @Override
    public Long component4() {
        return getAdminId();
    }

    @Override
    public Long component5() {
        return getPlaceId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value3() {
        return getModifiedAt();
    }

    @Override
    public Long value4() {
        return getAdminId();
    }

    @Override
    public Long value5() {
        return getPlaceId();
    }

    @Override
    public AdminPlaceMapRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AdminPlaceMapRecord value2(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public AdminPlaceMapRecord value3(LocalDateTime value) {
        setModifiedAt(value);
        return this;
    }

    @Override
    public AdminPlaceMapRecord value4(Long value) {
        setAdminId(value);
        return this;
    }

    @Override
    public AdminPlaceMapRecord value5(Long value) {
        setPlaceId(value);
        return this;
    }

    @Override
    public AdminPlaceMapRecord values(Long value1, LocalDateTime value2, LocalDateTime value3, Long value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdminPlaceMapRecord
     */
    public AdminPlaceMapRecord() {
        super(AdminPlaceMap.ADMIN_PLACE_MAP);
    }

    /**
     * Create a detached, initialised AdminPlaceMapRecord
     */
    public AdminPlaceMapRecord(Long id, LocalDateTime createdAt, LocalDateTime modifiedAt, Long adminId, Long placeId) {
        super(AdminPlaceMap.ADMIN_PLACE_MAP);

        setId(id);
        setCreatedAt(createdAt);
        setModifiedAt(modifiedAt);
        setAdminId(adminId);
        setPlaceId(placeId);
    }
}
