/*
 * This file is generated by jOOQ.
 */
package com.jay.getinline;


import com.jay.getinline.tables.Admin;
import com.jay.getinline.tables.AdminPlaceMap;
import com.jay.getinline.tables.Event;
import com.jay.getinline.tables.Place;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in getinline.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index EVENT_IDX1TFS9R9C898G38QI8E0DLU6P = Internal.createIndex(DSL.name("IDX1tfs9r9c898g38qi8e0dlu6p"), Event.EVENT, new OrderField[] { Event.EVENT.CREATED_AT }, false);
    public static final Index EVENT_IDX2LVUUDPUC6G9C0N2CXR2PNMRG = Internal.createIndex(DSL.name("IDX2lvuudpuc6g9c0n2cxr2pnmrg"), Event.EVENT, new OrderField[] { Event.EVENT.EVENT_END_DATETIME }, false);
    public static final Index ADMIN_IDX2W1TG47E7NYWR4SS5F5O6DEEH = Internal.createIndex(DSL.name("IDX2w1tg47e7nywr4ss5f5o6deeh"), Admin.ADMIN, new OrderField[] { Admin.ADMIN.MODIFIED_AT }, false);
    public static final Index PLACE_IDX3BRDEHMT496L9Q3T483KGF51K = Internal.createIndex(DSL.name("IDX3brdehmt496l9q3t483kgf51k"), Place.PLACE, new OrderField[] { Place.PLACE.MODIFIED_AT }, false);
    public static final Index ADMIN_PLACE_MAP_IDX3WMKAPIB2LSEF1WGVTDLBXRLB = Internal.createIndex(DSL.name("IDX3wmkapib2lsef1wgvtdlbxrlb"), AdminPlaceMap.ADMIN_PLACE_MAP, new OrderField[] { AdminPlaceMap.ADMIN_PLACE_MAP.MODIFIED_AT }, false);
    public static final Index PLACE_IDX6A3DYVNFILILK1RGAH2ALIJV1 = Internal.createIndex(DSL.name("IDX6a3dyvnfililk1rgah2alijv1"), Place.PLACE, new OrderField[] { Place.PLACE.PLACE_NAME }, false);
    public static final Index EVENT_IDX7U5BMYXOV0KFSSYVS5TST6VHD = Internal.createIndex(DSL.name("IDX7u5bmyxov0kfssyvs5tst6vhd"), Event.EVENT, new OrderField[] { Event.EVENT.EVENT_NAME }, false);
    public static final Index PLACE_IDX9GR49J4BACR9U3CQD32GNRK5D = Internal.createIndex(DSL.name("IDX9gr49j4bacr9u3cqd32gnrk5d"), Place.PLACE, new OrderField[] { Place.PLACE.CREATED_AT }, false);
    public static final Index EVENT_IDX9KGPWASF0C90QC7SMV8RMLHKF = Internal.createIndex(DSL.name("IDX9kgpwasf0c90qc7smv8rmlhkf"), Event.EVENT, new OrderField[] { Event.EVENT.EVENT_START_DATETIME }, false);
    public static final Index ADMIN_IDXF712BLMN5YX7C70U10ITPUGMR = Internal.createIndex(DSL.name("IDXf712blmn5yx7c70u10itpugmr"), Admin.ADMIN, new OrderField[] { Admin.ADMIN.CREATED_AT }, false);
    public static final Index PLACE_IDXGQPM65TD1SBN0EYGT4YHBIAPK = Internal.createIndex(DSL.name("IDXgqpm65td1sbn0eygt4yhbiapk"), Place.PLACE, new OrderField[] { Place.PLACE.ADDRESS }, false);
    public static final Index ADMIN_IDXL4RY5K9T9G70NOFFCVFLYNFIP = Internal.createIndex(DSL.name("IDXl4ry5k9t9g70noffcvflynfip"), Admin.ADMIN, new OrderField[] { Admin.ADMIN.PHONE_NUMBER }, false);
    public static final Index EVENT_IDXLUAWQ5ATYV2LXY2K0A23QVYUG = Internal.createIndex(DSL.name("IDXluawq5atyv2lxy2k0a23qvyug"), Event.EVENT, new OrderField[] { Event.EVENT.MODIFIED_AT }, false);
    public static final Index PLACE_IDXQWOBLN9FWBGEN2XK98I9MP176 = Internal.createIndex(DSL.name("IDXqwobln9fwbgen2xk98i9mp176"), Place.PLACE, new OrderField[] { Place.PLACE.PHONE_NUMBER }, false);
    public static final Index ADMIN_PLACE_MAP_IDXT78FEBI7P1DUIXRQIEJA2V4UE = Internal.createIndex(DSL.name("IDXt78febi7p1duixrqieja2v4ue"), AdminPlaceMap.ADMIN_PLACE_MAP, new OrderField[] { AdminPlaceMap.ADMIN_PLACE_MAP.CREATED_AT }, false);
}
