/*
 * This file is generated by jOOQ.
 */
package com.jay.getinline;


import com.jay.getinline.tables.Admin;
import com.jay.getinline.tables.AdminPlaceMap;
import com.jay.getinline.tables.Event;
import com.jay.getinline.tables.Place;


/**
 * Convenience access to all tables in getinline.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>getinline.admin</code>.
     */
    public static final Admin ADMIN = Admin.ADMIN;

    /**
     * The table <code>getinline.admin_place_map</code>.
     */
    public static final AdminPlaceMap ADMIN_PLACE_MAP = AdminPlaceMap.ADMIN_PLACE_MAP;

    /**
     * The table <code>getinline.event</code>.
     */
    public static final Event EVENT = Event.EVENT;

    /**
     * The table <code>getinline.place</code>.
     */
    public static final Place PLACE = Place.PLACE;
}
